# Funding Development

To help our development you can donate to our LEET server by these ways :

Android) Download the LEET Donations app from the Play Store and then put our server IP : mythicpvp.pocket.pe and port : 16859. Then select the amount you want to donate by the available options.

iOS) Download the LEET Donations app from the App Store and then put our server IP : mythicpvp.pocket.pe and port : 16859. Then select the amount you want to donate by the available options.
